-- Legacy one-off removed during the infrastructure handover.
-- Administrative roles and passwords must never be provisioned from
-- repository migrations or tied to accounts owned by the previous vendor.
